#!/usr/bin/env bash
#   █████╗ ██████╗ ██████╗ ███████╗    ██╗      █████╗ ██╗   ██╗███╗   ██╗ ██████╗██╗  ██╗███████╗██████╗
#  ██╔══██╗██╔══██╗██╔══██╗██╔════╝    ██║     ██╔══██╗██║   ██║████╗  ██║██╔════╝██║  ██║██╔════╝██╔══██╗
#  ███████║██████╔╝██████╔╝███████╗    ██║     ███████║██║   ██║██╔██╗ ██║██║     ███████║█████╗  ██████╔╝
#  ██╔══██║██╔═══╝ ██╔═══╝ ╚════██║    ██║     ██╔══██║██║   ██║██║╚██╗██║██║     ██╔══██║██╔══╝  ██╔══██╗
#  ██║  ██║██║     ██║     ███████║    ███████╗██║  ██║╚██████╔╝██║ ╚████║╚██████╗██║  ██║███████╗██║  ██║
#  ╚═╝  ╚═╝╚═╝     ╚═╝     ╚══════╝    ╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
# Script to control prefered apps to launch for all themes
# Author: z0mbi3
# url:    https://github.com/gh0stzk

read -r RICETHEME < "$HOME"/.config/i3/config.d/.rice

WIDGET_DIR="$HOME/.config/i3/rices/$RICETHEME/eww"

case "$1" in
    --menu)
        # rofi -show drun -theme "$HOME"/.config/i3/src/Launcher.rasi 
        rofi -show drun -theme "$HOME"/.config/i3/rices/$RICETHEME/rofi/rofi_launchers/launchpad_v3.rasi
        ;;
    --rice)
        ~/.config/i3/src/RiceSelector
        ;;
    --terminal)
        ~/.config/i3/src/Term --terminal
        ;;
    --floating)
        ~/.config/i3/src/Term --floating
        ;;
    --update-paru)
        ~/.config/i3/src/Term --update-paru
        ;;
    --update)
        ~/.config/i3/src/Term --update
        ;;
    --checkupdates)
        ~/.config/i3/src/Term --checkupdates
        ;;
    --netmanager)
		~/.config/i3/src/NetManagerDM
		;;
    --ranger)
        ~/.config/i3/src/Term --ranger
        ;;
    --yazi)
        ~/.config/i3/src/Term --yazi
        ;;
    --nvim)
        ~/.config/i3/src/Term --nvim
        ;;
    --music)
        ~/.config/i3/src/Term --music
        ;;
    --fetch)
        ~/.config/i3/src/Term --fetch
        ;;
    --ssh)
        ~/.config/i3/src/Term --connect
        ;;
    "--monitor")
        ~/.config/i3/src/Term --process
        ;;
        # Apps
    --filemanager)
        thunar
        ;;
    --browser)
        firefox
        ;;
    --editor)
        code
        ;;
    --telegram)
        telegram-desktop
        ;;
    --whats)
        whatsdesk --disable-gpu
        ;;
    --soundcontrol)
        pavucontrol
        ;;
        # Eww Widgets
    --KeyHelp)
		eww -c "$WIDGET_DIR" open --toggle csheet
		;;    
    --powermenu)
        eww -c "$WIDGET_DIR" open --toggle powermenu
        ;;
    --usercard)
        eww -c "$WIDGET_DIR" open --toggle launchermenu
        ;;
    --player)
        eww -c "$WIDGET_DIR" open --toggle music
        ;;
    --calendar)
        eww -c "$WIDGET_DIR" open --toggle date
        ;;
    --KeyHelp)
		eww -c "$WIDGET_DIR" open --toggle csheet
		;;
    *)
        echo "Invalid Option"
        ;;
esac
