#!/usr/bin/env bash

# Some vars
i3_dir="$HOME/.config/i3"
RICETHEME="$i3_dir/config.d/.rice"
rofi_command="rofi -dmenu -theme $i3_dir/src/rofi-themes/RiceSelector.rasi"
i3_rice_in_config=$(< "$RICETHEME")

# Variables to try to define the correct size of the images for your resolution
monitor_res=$(xdpyinfo | awk '/dimensions/{print $2}' | cut -d 'x' -f1)
monitor_scale=$(xdpyinfo | awk '/resolution/{print $2}' | cut -d 'x' -f1)
monitor_res=$(( monitor_res * 17 / monitor_scale ))
rofi_override="element-icon{size:${monitor_res}px;}"

# Function to check for required commands
check_requirements() {
    for cmd in xdpyinfo rofi feh i3-msg; do
        if ! command -v "$cmd" > /dev/null 2>&1; then
            dunstify "Missing package" "Please install the $cmd package to continue" -u critical
            exit 1
        fi
    done
}

# Function to list available rices
list_rices() {
    options=()
    index=0
    selected_index=0
    current_rice=$(< "$RICETHEME")

    for rice_dir in "$i3_dir"/rices/*/; do
        rice_name=$(basename "$rice_dir")
        options+=("$rice_name")

        # Check if the current rice matches the current iteration rice
        if [[ "$current_rice" == "$rice_name" ]]; then
            selected_index=$index
        fi

        ((index++))
    done

    echo "${options[@]}"
    echo "$selected_index"
}

# Function to show the rofi selection menu
show_rofi_menu() {
    local options=("$@")
    local selected_index=${options[-1]}
    unset options[-1]

    printf "%s\n" "${options[@]}" | while read -r A ; do
        echo -en "$A\x00icon\x1f$i3_dir/rices/$A/preview.webp\n"
    done | $rofi_command -theme-str "$rofi_override" -selected-row "$selected_index"
}

# Function to update the current rice
update_rice() {
    local selected="$1"
    echo "$selected" > "$RICETHEME"

    # Находим случайное изображение в папке с обоями для выбранной темы
    new_wall=$(find "$HOME/.config/i3/rices/$selected/walls/light" -name "*.png" -o -name "*.webp" -o -name "*.jpeg" -o -name "*.jpg" | shuf -n 1)
    new_wall=$(basename "$new_wall")  # Получаем только имя файла

    echo "Selected theme: $selected"
    echo "New wallpaper: $new_wall"

    # Применяем обои "на лету" с помощью feh
    feh --no-fehbg --bg-fill "$HOME/.config/i3/rices/$selected/walls/light/$new_wall"

    # Обновляем строку с обоями в autostart
    sed -i "/exec --no-startup-id feh -z --no-fehbg --bg-fill /c\exec --no-startup-id feh -z --no-fehbg --bg-fill \$HOME/.config/i3/rices/$selected/walls/light/$new_wall" "$HOME/.config/i3/config.d/autostart"

    # Обновляем текущую тему в autostart
    sed -i "s/$i3_rice_in_config/$selected/g" "$HOME/.config/i3/config.d/autostart"

    # Перезапускаем i3 только если это необходимо (например, при изменении темы)
    if [[ "$selected" != "$i3_rice_in_config" ]]; then
        i3-msg restart
    fi
}

# Main function
main() {
    check_requirements

    local options_and_index=($(list_rices))
    local selected_index=${options_and_index[-1]}
    local options=("${options_and_index[@]:0:${#options_and_index[@]}-1}")

    local selected=$(show_rofi_menu "${options[@]}" "$selected_index")

    # Exit if no selection was made or if the selection is the same as the current rice
    [[ -n "$selected" && "$selected" != "$(cat "$RICETHEME")" ]] || exit 0

    update_rice "$selected"
}

main
exit 0