#!/usr/bin/env bash
#  ███████╗██╗   ██╗███████╗████████╗███████╗███╗   ███╗    ██╗   ██╗ █████╗ ██████╗ ███████╗
#  ██╔════╝╚██╗ ██╔╝██╔════╝╚══██╔══╝██╔════╝████╗ ████║    ██║   ██║██╔══██╗██╔══██╗██╔════╝
#  ███████╗ ╚████╔╝ ███████╗   ██║   █████╗  ██╔████╔██║    ██║   ██║███████║██████╔╝███████╗
#  ╚════██║  ╚██╔╝  ╚════██║   ██║   ██╔══╝  ██║╚██╔╝██║    ╚██╗ ██╔╝██╔══██║██╔══██╗╚════██║
#  ███████║   ██║   ███████║   ██║   ███████╗██║ ╚═╝ ██║     ╚████╔╝ ██║  ██║██║  ██║███████║
#  ╚══════╝   ╚═╝   ╚══════╝   ╚═╝   ╚══════╝╚═╝     ╚═╝      ╚═══╝  ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝


CONFIG_FILE="$HOME/.config/i3/config.d/system.ini"
SFILE="$HOME/.config/i3/config.d/.sys"

# Check if the .sys file already exists
[[ -f "$SFILE" ]] && exit 0 # The file exists, exit without doing anything

# Function to get and set values
function setup_system_vars() {
    # Network interfaces (primary and secondary)
    # readarray -t ALL_NET < <(ip -o link show up | awk -F': ' '{print $2}' | grep -vE '^(lo|docker|veth|br-)')

	PRIMARY_NET=$(ip -o route get 1 | awk '{print $5; exit}')
	SECONDARY_NET=$(ip -o link show | sed -rn '/^[0-9]+: en/{s/.: ([^:]*):.*/\1/p}')

    [[ -n "$PRIMARY_NET" ]] && sed -i "s/sys_wireless_interface = .*/sys_wireless_interface = $PRIMARY_NET/" "$CONFIG_FILE"
    [[ -n "$SECONDARY_NET" ]] && sed -i "s/sys_network_interface = .*/sys_network_interface = $SECONDARY_NET/" "$CONFIG_FILE"

    # Graphics card (backlight)
    CARD=$(find /sys/class/backlight -maxdepth 1 -type l | head -n1 | xargs basename)
    [[ -n "$CARD" ]] && sed -i "s/sys_graphics_card = .*/sys_graphics_card = $CARD/" "$CONFIG_FILE"

    # Battery and adapter
    BATTERY=$(find /sys/class/power_supply -maxdepth 1 -type l -name "BAT*" | head -n1 | xargs basename)
    ADAPTER=$(find /sys/class/power_supply -maxdepth 1 -type l -name "A[CD]*" | head -n1 | xargs basename)

    [[ -n "$BATTERY" ]] && sed -i "s/sys_battery = .*/sys_battery = $BATTERY/" "$CONFIG_FILE"
    [[ -n "$ADAPTER" ]] && sed -i "s/sys_adapter = .*/sys_adapter = $ADAPTER/" "$CONFIG_FILE"

    # Connected moditor
    CONECT=$(xrandr | grep " connected " | awk '{ print$1 }')

    [[ -n "$CONECT" ]] && sed -i "s/sys_monitor = .*/sys_monitor = $CONECT/" "$CONFIG_FILE"
}

# Ejecutar la configuración
setup_system_vars

# Crear el archivo .sys para indicar que la configuración ya se ha realizado
touch "$SFILE"
