#!/usr/bin/env bash

config="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-3.0/settings.ini"
[ ! -f "$config" ] && exit 1

get_setting() {
    grep "^$1" "$config" | sed 's/.*=\s*//'
}

gtk_theme=$(get_setting 'gtk-theme-name')
icon_theme=$(get_setting 'gtk-icon-theme-name')
cursor_theme=$(get_setting 'gtk-cursor-theme-name')

[ -n "$gtk_theme" ] && gsettings set org.gnome.desktop.interface gtk-theme "$gtk_theme"
[ -n "$icon_theme" ] && gsettings set org.gnome.desktop.interface icon-theme "$icon_theme"
[ -n "$cursor_theme" ] && gsettings set org.gnome.desktop.interface cursor-theme "$cursor_theme"

# Для libadwaita приложений
export GTK_THEME="$gtk_theme"
export ICON_THEME="$icon_theme"