#!/usr/bin/env bash
#
#  ███████╗ ██████╗██████╗ ███████╗███████╗███╗   ██╗    ██╗      ██████╗  ██████╗██║  ██╗
#  ██╔════╝██╔════╝██╔══██╗██╔════╝██╔════╝████╗  ██║    ██║     ██╔═══██╗██╔════╝██║ ██╔╝
#  ███████╗██║     ██████╔╝█████╗  █████╗  ██╔██╗ ██║    ██║     ██║   ██║██║     █████╔╝
#  ╚════██║██║     ██╔══██╗██╔══╝  ██╔══╝  ██║╚██╗██║    ██║     ██║   ██║██║     ██╔═██╗
#  ███████║╚██████╗██║  ██║███████╗███████╗██║ ╚████║    ███████╗╚██████╔╝╚██████╗██║  ██╗
#  ╚══════╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚══════╝╚═╝  ╚═══╝    ╚══════╝ ╚═════╝  ╚═════╝╚═╝  ╚═╝
#	gh0stzk - https://github.com/gh0stzk/dotfiles
#	15.10.2024 14:26:09
#	Dependencies - i3lock-color, xkb-switch
#

TEMP_IMAGE="/tmp/i3lock.jpg"

# Путь к конфигурационному файлу
CONFIG_FILE="$HOME/.config/screenlocker.conf"

# Значения по умолчанию
bg=1e1e2e       # Base (фон)
fg=cdd6f4       # Text (основной текст)
ring=89b4fa     # Blue (кольцо индикатора)
wrong=f38ba8    # Red (ошибки)
date=cdd6f4     # Text (дата и время)
verify=a6e3a1   # Green (подтверждение)

time_font="MesloLGS NF:style=Bold"
date_font="MesloLGS NF"
verif_font="MesloLGS NF"
greeter_font="MesloLGS NF"
wrong_font="MesloLGS NF"

ind_pos="960:600"
time_pos="960:450"
date_pos="960:500"
greeter_pos="100:980"
wrong_pos="960:700"
verif_pos="960:700"

# Загрузка конфигурации
if [[ -f "$CONFIG_FILE" ]]; then
    source "$CONFIG_FILE"
else
    echo "Config file not found. Using default settings."
fi

# Check dependencies
command -v maim >/dev/null 2>&1 || { echo >&2 "maim is required but it's not installed. Aborting."; exit 1; }
command -v magick >/dev/null 2>&1 || { echo >&2 "ImageMagick is required but it's not installed. Aborting."; exit 1; }
command -v i3lock >/dev/null 2>&1 || { echo >&2 "i3lock-color is required but it's not installed. Aborting."; exit 1; }
command -v xkb-switch >/dev/null 2>&1 || { echo >&2 "xkb-switch is required but it's not installed. Aborting."; exit 1; }

# Remove temporary file on exit
trap 'rm -f $TEMP_IMAGE' EXIT

get_time_based_theme() {
    current_hour=$(date +%H)
    if [[ $current_hour -ge 18 || $current_hour -lt 6 ]]; then
        echo "dark"
    else
        echo "light"
    fi
}

get_keyboard_layout() {
    layout=$(xkb-switch)
    case $layout in
        us) echo "EN";;
        ru) echo "RU";;
        *) echo "$layout";;  # Если раскладка не распознана, отображаем её как есть
    esac
}

default_lockscreen () {
    xkb-switch -s us  # Устанавливаем раскладку на EN перед блокировкой
    maim -d 0.3 -u ${TEMP_IMAGE}
    magick $TEMP_IMAGE -blur 5x4 $TEMP_IMAGE
    layout=$(get_keyboard_layout)
    i3lock -n --force-clock -i $TEMP_IMAGE -e --indicator \
        --radius=30 --ring-width=60 --inside-color=$bg \
        --ring-color=$ring --insidever-color=$verify --ringver-color=$verify \
        --insidewrong-color=$wrong --ringwrong-color=$wrong --line-uses-inside \
        --keyhl-color=$verify --separator-color=$verify --bshl-color=$verify \
        --time-str="%H:%M" --time-size=140 --date-str="%a, %d %b" \
        --date-size=45 --verif-text="Verifying Password..." --wrong-text="Wrong Password!" \
        --noinput-text="" --greeter-text="Layout: $layout" --ind-pos="$ind_pos" \
        --time-font="$time_font" --date-font="$date_font" --verif-font="$verif_font" \
        --greeter-font="$greeter_font" --wrong-font="$wrong_font" --verif-size=23 \
        --greeter-size=23 --wrong-size=23 --time-pos="$time_pos" \
        --date-pos="$date_pos" --greeter-pos="$greeter_pos" --wrong-pos="$wrong_pos" \
        --verif-pos="$verif_pos" --date-color=$date --time-color=$date \
        --greeter-color=$fg --wrong-color=$wrong --verif-color=$verify \
        --pointer=default --refresh-rate=0 \
        --pass-media-keys --pass-volume-keys
}

rice_lockscreen () {
    # Current Rice
    if [[ ! -f "$HOME/.config/i3/config.d/.rice" ]]; then
        echo "Rice configuration file not found. Aborting."
        exit 1
    fi
    read -r RICE < "$HOME"/.config/i3/config.d/.rice

    # Wallpapers dir
    theme=$(get_time_based_theme)  # или theme=$(get_system_theme) для интеграции с системной темой
    image_dir="$HOME/.config/i3/rices/${RICE}/walls/${theme}"
    if [[ ! -d "$image_dir" ]]; then
        echo "Wallpapers directory not found. Aborting."
        exit 1
    fi

    # Select random image
    lock_image=$(find "$image_dir" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" \) | shuf -n 1)

    # If the image is *.webp convert to /tmp/lock_image.jpg
    if [[ "$lock_image" == *.webp ]]; then
        if ! magick "$lock_image" "$TEMP_IMAGE"; then
            echo "Failed to convert webp image. Aborting."
            exit 1
        fi
    fi

    xkb-switch -s us  # Устанавливаем раскладку на EN перед блокировкой
    layout=$(get_keyboard_layout)
    i3lock -n --force-clock -i $TEMP_IMAGE --scale -e --indicator \
        --radius=30 --ring-width=60 --inside-color=$bg \
        --ring-color=$ring --insidever-color=$verify --ringver-color=$verify \
        --insidewrong-color=$wrong --ringwrong-color=$wrong --line-uses-inside \
        --keyhl-color=$verify --separator-color=$verify --bshl-color=$verify \
        --time-str="%H:%M" --time-size=140 --date-str="%a, %d %b" \
        --date-size=45 --verif-text="Verifying Password..." --wrong-text="Wrong Password!" \
        --noinput-text="" --greeter-text="Layout: $layout" --ind-pos="$ind_pos" \
        --time-font="$time_font" --date-font="$date_font" --verif-font="$verif_font" \
        --greeter-font="$greeter_font" --wrong-font="$wrong_font" --verif-size=23 \
        --greeter-size=23 --wrong-size=23 --time-pos="$time_pos" \
        --date-pos="$date_pos" --greeter-pos="$greeter_pos" --wrong-pos="$wrong_pos" \
        --verif-pos="$verif_pos" --date-color=$date --time-color=$date \
        --greeter-color=$fg --wrong-color=$wrong --verif-color=$verify \
        --pointer=default --refresh-rate=0 \
        --pass-media-keys --pass-volume-keys
}

if [[ $# -gt 2 ]]; then
    echo "Too many arguments. Use -h for help."
    exit 1
fi

case $1 in
    -r|--rice)
        rice_lockscreen;;
    -h|--help)
        echo -e "ScreenLocker [options]
Note: If an option is not specified, the screen locks with a screenshot with a blur effect.

Options:
    [-r] [--rice]  Set the screen locker with a random wallpaper of the current theme.
    [-t] [--theme] Set the theme (dark or light) for the wallpaper.\n";;
    -t|--theme)
        if [[ -z $2 ]]; then
            echo "Theme not specified. Use -h for help."
            exit 1
        fi
        theme=$2
        rice_lockscreen;;
    *)
        if [[ -n $1 ]]; then
            echo "Invalid option: $1. Use -h for help."
            exit 1
        fi
        default_lockscreen;;
esac