#!/usr/bin/env bash

set -x

hidden=/tmp/syshide.lock
file="$HOME/.config/i3/polybar/Tokio_night/modules"

	if [[ ! -e $hidden ]]; then
			polybar-msg action "#systray.hook.1"
			killall stalonetray
			touch "$hidden"
			sed -i 's/systray\ninitial=.*/systray\ninitial=2/g' "$file"
		else
			polybar-msg action "#systray.hook.0"
            stalonetray
			rm "$hidden"
			sed -i 's/systray\ninitial=.*/systray\ninitial=1/g' "$file"
	fi
