#!/bin/bash

read -r RICETHEME < "$HOME"/.config/i3/config.d/.rice

# Use shuf to output a random line from the file
random_line=$(shuf -n 1 "$HOME/.config/i3/rices/$RICETHEME/eww/Main/scripts/tips.lst")
echo "$random_line"
