# i3status
# Autogenerated from man page /usr/share/man/man1/i3status.1.gz
complete -c i3status -s c -l config -d 'Specifies an alternate configuration file path'
complete -c i3status -s h -l help -d 'Print the verison and a minimal syntax'
complete -c i3status -s v -l version -d 'Print the version and any build configuration'
complete -c i3status -l run-once -d 'Only run once instead of looping'
complete -c i3status -o fn -o misc-fixed-medium-r-normal--13-120-75-75-C-70-iso8859-1 -d 'USING I3STATUS WITH XMOBAR'

