# jgmenu-ob
# Autogenerated from man page /usr/share/man/man1/jgmenu-ob.1.gz
complete -c jgmenu-ob -l cmd -d 'Specify command to produce openbox XML menu data'
complete -c jgmenu-ob -l tag -d 'Specify value of root ^tag()'

