# jgmenu-apps
# Autogenerated from man page /usr/share/man/man1/jgmenu-apps.1.gz
complete -c jgmenu-apps -l help -d 'Show help message and exit'
complete -c jgmenu-apps -l no-prepend -d 'Do not output ~/. config/jgmenu/prepend. csv before root menu'
complete -c jgmenu-apps -l no-append -d 'Do not output ~/. config/jgmenu/append'

