# mariadb-config
# Autogenerated from man page /usr/share/man/man1/mariadb-config.1.gz
complete -c mariadb-config -l cflags
complete -c mariadb-config -l include -d 'for more portable options that contain only include paths.  oc o 2. 3'
complete -c mariadb-config -l libmysqld-libs
complete -c mariadb-config -l embedded
complete -c mariadb-config -l libs
complete -c mariadb-config -l libs_r
complete -c mariadb-config -l plugindir
complete -c mariadb-config -l port
complete -c mariadb-config -l socket
complete -c mariadb-config -l variable
complete -c mariadb-config -l version

