# pasystray
# Autogenerated from man page /usr/share/man/man1/pasystray.1.gz
complete -c pasystray -s V -l version -d 'Show the program version'
complete -c pasystray -s d -l debug -d 'Print debugging information'
complete -c pasystray -s m -l volume-max -d 'Set the maximum volume (in percent)'
complete -c pasystray -s i -l volume-inc -d 'Set the volume increment'
complete -c pasystray -s r -l reverse-scroll -d 'Reverse the direction of volume adjustment with the mouse scroll wheel'
complete -c pasystray -s t -l no-icon-tooltip -d 'Disable the status icon tooltip for the connected state'
complete -c pasystray -s n -l no-notify -d 'Disable all notifications.  Deprecated; use --notify=none instead'
complete -c pasystray -s a -l always-notify -d 'Enable notifications for all changes in pulsaudio'
complete -c pasystray -l include-monitors -d 'Show monitor sources'
complete -c pasystray -s g -l key-grabbing -d 'Enable keyboard volume control and mute keys to adjust volume settings'
complete -c pasystray -s N -l notify -d 'Set notification options; use --notify=help for a list of valid options'

