# picom-trans
# Autogenerated from man page /usr/share/man/man1/picom-trans.1.gz
complete -c picom-trans -s w -l window
complete -c picom-trans -s n -l name
complete -c picom-trans -s c -l current
complete -c picom-trans -s s -l select
complete -c picom-trans -s o -l opacity
complete -c picom-trans -s g -l get
complete -c picom-trans -s d -l delete
complete -c picom-trans -s t -l toggle
complete -c picom-trans -s r -l reset

