# picom
# Autogenerated from man page /usr/share/man/man1/picom.1.gz
complete -c picom -s h -l help
complete -c picom -s r -l shadow-radius
complete -c picom -s o -l shadow-opacity
complete -c picom -s l -l shadow-offset-x
complete -c picom -s t -l shadow-offset-y
complete -c picom -s I -l fade-in-step
complete -c picom -s O -l fade-out-step
complete -c picom -s D -l fade-delta
complete -c picom -s c -l shadow
complete -c picom -s f -l fading
complete -c picom -s i -l inactive-opacity
complete -c picom -s e -l frame-opacity
complete -c picom -s b -l daemon
complete -c picom -l log-level
complete -c picom -l log-file
complete -c picom -l legacy-backends
complete -c picom -l show-all-xerrors
complete -c picom -l config
complete -c picom -l write-pid-path
complete -c picom -l plugins
complete -c picom -l shadow-color
complete -c picom -l shadow-red
complete -c picom -l shadow-green
complete -c picom -l shadow-blue
complete -c picom -l inactive-opacity-override
complete -c picom -l active-opacity
complete -c picom -l inactive-dim
complete -c picom -l corner-radius
complete -c picom -l corner-radius-rules
complete -c picom -l rounded-corners-exclude
complete -c picom -l no-frame-pacing
complete -c picom -l mark-wmwin-focused
complete -c picom -l mark-ovredir-focused
complete -c picom -l no-fading-openclose
complete -c picom -l no-fading-destroyed-argb
complete -c picom -l shadow-ignore-shaped
complete -c picom -l detect-rounded-corners
complete -c picom -l detect-client-opacity
complete -c picom -l vsync -l no-vsync
complete -c picom -l use-ewmh-active-win
complete -c picom -l unredir-if-possible
complete -c picom -l unredir-if-possible-delay
complete -c picom -l unredir-if-possible-exclude
complete -c picom -l shadow-exclude
complete -c picom -l clip-shadow-above
complete -c picom -l fade-exclude
complete -c picom -l focus-exclude
complete -c picom -l inactive-dim-fixed
complete -c picom -l detect-transient
complete -c picom -l detect-client-leader
complete -c picom -l blur-method -l blur-size -l blur-deviation -l blur-strength
complete -c picom -l blur-background
complete -c picom -l blur-background-frame
complete -c picom -l blur-background-fixed
complete -c picom -l blur-kern
complete -c picom -l blur-background-exclude
complete -c picom -l resize-damage
complete -c picom -l invert-color-include
complete -c picom -l opacity-rule
complete -c picom -l crop-shadow-to-monitor
complete -c picom -l backend
complete -c picom -l glx-no-stencil
complete -c picom -l glx-no-rebind-pixmap
complete -c picom -l no-use-damage
complete -c picom -l xrender-sync-fence
complete -c picom -l glx-fshader-win
complete -c picom -l force-win-blend
complete -c picom -l dbus
complete -c picom -l benchmark
complete -c picom -l benchmark-wid
complete -c picom -l no-ewmh-fullscreen
complete -c picom -l max-brightness
complete -c picom -l transparent-clipping
complete -c picom -l transparent-clipping-exclude
complete -c picom -l window-shader-fg
complete -c picom -l window-shader-fg-rule
complete -c picom -l dithered-present

