# sdffilter
# Autogenerated from man page /usr/share/man/man1/sdffilter.1.gz
complete -c sdffilter -s h -l help -d 'Print this help message and exit'
complete -c sdffilter -s p -l path -d 'Report only paths matching this regex'
complete -c sdffilter -s f -l field -d 'Report only fields matching this regex'
complete -c sdffilter -s t -l time -d 'Report only these times (n) or time ranges (ff. lf) for \'timeSamples\' fields'
complete -c sdffilter -l timeTolerance -d 'Report times that are close to those requested within this relative tolerance'
complete -c sdffilter -l arraySizeLimit -d 'Truncate arrays with more than this many elements'
complete -c sdffilter -l timeSamplesSizeLimit -d 'Truncate timeSamples with more than this many values'
complete -c sdffilter -s o -l out -d 'Direct output to this file'
complete -c sdffilter -l outputType -d 'Specify output format; \'summary\' reports overall statistics, \'outline\' is a f…'
complete -c sdffilter -l sortBy -d 'Group \'outline\' output by either path or field'
complete -c sdffilter -l noValues -d 'Do not report field values'

