# usdBakeMaterialX
# Autogenerated from man page /usr/share/man/man1/usdBakeMaterialX.1.gz
complete -c usdBakeMaterialX -s h -l help -d 'show this help message and exit'
complete -c usdBakeMaterialX -l width -d 'Specify the width of the baked textures'
complete -c usdBakeMaterialX -l height -d 'Specify the height of the baked textures'
complete -c usdBakeMaterialX -l hdr -d 'Save images to hdr format'
complete -c usdBakeMaterialX -l average -d 'Average baked images to generate constant values'

