# usddumpcrate
# Autogenerated from man page /usr/share/man/man1/usddumpcrate.1.gz
complete -c usddumpcrate -s h -l help -d 'show this help message and exit'
complete -c usddumpcrate -s s -l summary -d 'report only a short summary'

