# usdedit
# Autogenerated from man page /usr/share/man/man1/usdedit.1.gz
complete -c usdedit -s h -l help -d 'show this help message and exit'
complete -c usdedit -s n -l noeffect -d 'Do not edit the file'
complete -c usdedit -s f -l forcewrite -d 'Override file permissions to allow writing'
complete -c usdedit -s p -l prefix -d 'Provide a prefix for the temporary file name'

