# usdfixbrokenpixarschemas
# Autogenerated from man page /usr/share/man/man1/usdfixbrokenpixarschemas.1.gz
complete -c usdfixbrokenpixarschemas -s h -l help -d 'show this help message and exit'
complete -c usdfixbrokenpixarschemas -l backup -d 'optional backup file path, if none provided creates a <inputFile>. bck'
complete -c usdfixbrokenpixarschemas -s v -l verbose -d 'Enable verbose mode'

