# usdgenschemafromsdr
# Autogenerated from man page /usr/share/man/man1/usdgenschemafromsdr.1.gz
complete -c usdgenschemafromsdr -s h -l help -d 'show this help message and exit'
complete -c usdgenschemafromsdr -l noreadme -d 'When specified a README'
complete -c usdgenschemafromsdr -s v -l validate -d 'This is passed to usdGenSchem to verify that the source files are unchanged'

