# usdtree
# Autogenerated from man page /usr/share/man/man1/usdtree.1.gz
complete -c usdtree -s h -l help -d 'Print this help message and exit'
complete -c usdtree -l unloaded -d 'Do not load payloads'
complete -c usdtree -s a -l attributes -d 'Display authored attributes'
complete -c usdtree -s m -l metadata -d 'Display authored metadata (active and kind are part of the label and not show…'
complete -c usdtree -s s -l simple -d 'Only display prim names: no specifier, kind or active state'
complete -c usdtree -s f -l flatten -d 'Compose the stage with the input file as the root layer and write the flatten…'
complete -c usdtree -l flattenLayerStack -d 'Flatten the layer stack with the given root layer'
complete -c usdtree -l mask -d 'Limit stage population to these prims, their descendants and ancestors'

