#!/usr/bin/env bash
#   █████╗ ██████╗ ██████╗ ███████╗    ██╗      █████╗ ██╗   ██╗███╗   ██╗ ██████╗██╗  ██╗███████╗██████╗
#  ██╔══██╗██╔══██╗██╔══██╗██╔════╝    ██║     ██╔══██╗██║   ██║████╗  ██║██╔════╝██║  ██║██╔════╝██╔══██╗
#  ███████║██████╔╝██████╔╝███████╗    ██║     ███████║██║   ██║██╔██╗ ██║██║     ███████║█████╗  ██████╔╝
#  ██╔══██║██╔═══╝ ██╔═══╝ ╚════██║    ██║     ██╔══██║██║   ██║██║╚██╗██║██║     ██╔══██║██╔══╝  ██╔══██╗
#  ██║  ██║██║     ██║     ███████║    ███████╗██║  ██║╚██████╔╝██║ ╚████║╚██████╗██║  ██║███████╗██║  ██║
#  ╚═╝  ╚═╝╚═╝     ╚═╝     ╚══════╝    ╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
# Script to control prefered apps to launch for all themes
# Author: z0mbi3
# url:    https://github.com/gh0stzk

WIDGET_DIR="$HOME/.config/i3/eww"

case "$1" in
    --menu)
        rofi -show drun -theme "$HOME"/.config/i3/scripts/Launcher.rasi 
        ;;
    --rice)
        ~/.config/i3/scripts/RiceSelector
        ;;
    --terminal)
        ~/.config/i3/scripts/Term --terminal
        ;;
    --floating)
        ~/.config/i3/scripts/Term --floating
        ;;
    --update-paru)
        ~/.config/i3/scripts/Term --update-paru
        ;;
    --update-pacman)
        ~/.config/i3/scripts/Term --update-pacman
        ;;
    --update-garuda)
        ~/.config/i3/scripts/Term --update-garuda
        ;;
    --checkupdates)
        ~/.config/i3/scripts/Term --checkupdates
        ;;
    --netmanager)
		~/.config/i3/scripts/NetManagerDM
		;;
    --ranger)
        ~/.config/i3/scripts/Term --ranger
        ;;
    --nvim)
        ~/.config/i3/scripts/Term --nvim
        ;;
    --music)
        ~/.config/i3/scripts/Term --music
        ;;
    --fetch)
        ~/.config/i3/scripts/Term --fetch
        ;;
        # Apps
    --filemanager)
        thunar
        ;;
    --browser)
        firefox
        ;;
    --editor)
        code
        ;;
    --telegram)
        telegram-desktop
        ;;
    --whats)
        whatsdesk --disable-gpu
        ;;
    --soundcontrol)
        pavucontrol
        ;;
        # Eww Widgets
    --KeyHelp)
		eww -c "$WIDGET_DIR" open --toggle csheet
		;;    
    --powermenu)
        eww -c "$WIDGET_DIR" open --toggle powermenu
        ;;
    --usercard)
        eww -c "$WIDGET_DIR" open --toggle launchermenu
        ;;
    --player)
        eww -c "$WIDGET_DIR" open --toggle music
        ;;
    --calendar)
        eww -c "$WIDGET_DIR" open --toggle date
        ;;
    *)
        echo "Invalid Option"
        ;;
esac
