#!/usr/bin/env bash
#  ██████╗ ██╗ ██████╗███████╗
#  ██╔══██╗██║██╔════╝██╔════╝        gh0stzk
#  ██████╔╝██║██║     █████╗          https://github.com/gh0stzk/dotfiles
#  ██╔══██╗██║██║     ██╔══╝          08.12.2023 08:48:08
#  ██║  ██║██║╚██████╗███████╗
#  ╚═╝  ╚═╝╚═╝ ╚═════╝╚══════╝
#
#            ███████╗███████╗██╗     ███████╗ ██████╗████████╗ ██████╗ ██████╗
#            ██╔════╝██╔════╝██║     ██╔════╝██╔════╝╚══██╔══╝██╔═══██╗██╔══██╗
#            ███████╗█████╗  ██║     █████╗  ██║        ██║   ██║   ██║██████╔╝
#            ╚════██║██╔══╝  ██║     ██╔══╝  ██║        ██║   ██║   ██║██╔══██╗
#            ███████║███████╗███████╗███████╗╚██████╗   ██║   ╚██████╔╝██║  ██║
#            ╚══════╝╚══════╝╚══════╝╚══════╝ ╚═════╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝
#
#set -x
# Some vars
user=$(whoami)
i3_dir="$HOME/.config/i3"
current_rice_file="$i3_dir/.rice"
preview_dir="$i3_dir/rices/${options[*]}"
rofi_command="rofi -dmenu -theme $i3_dir/scripts/RiceSelector.rasi"
i3_rice_in_config=$(< "$current_rice_file")


# Variables to try to define the correct size of the images for your resolution
monitor_res=$(xdpyinfo | awk '/dimensions/{print $2}' | cut -d 'x' -f1)
monitor_scale=$(xdpyinfo | awk '/resolution/{print $2}' | cut -d 'x' -f1)
monitor_res=$(( monitor_res * 17 / monitor_scale ))
rofi_override="element-icon{size:${monitor_res}px;}"

# Verificar si xdpyinfo e imagemagick están instalados
if ! command -v xdpyinfo > /dev/null 2>&1; then
    dunstify "Missing package" "Please install the xorg-xdpyinfo package to continue" -u critical
    exit 1
fi

# List rices
options=()
index=0
selected_index=0
current_rice=$(< "$current_rice_file")

for rice_dir in "$i3_dir"/rices/*/; do
    rice_name=$(basename "$rice_dir")
    options+=("$rice_name")

    # Check if the current rice matches the current iteration rice
    if [[ "$current_rice" == "$rice_name" ]]; then
        selected_index=$index
    fi

    ((index++))
done

# Show the rofi selection menu with the starting point set to the current rice and store the result in a variable.
selected=$(printf "%s\n" "${options[@]}" | while read -r A ; do  echo -en "$A\x00icon\x1f${preview_dir}$A/preview.webp\n" ; done | $rofi_command -theme-str "$rofi_override" -selected-row "$selected_index")

# If a valid option was selected, write the value to the configuration file and restart BSPWM.
[[ -n "$selected" && "$selected" != "$current_rice" ]] || exit 1
echo "$selected" > "$current_rice_file"

sed -i "s/"$i3_rice_in_config"/"$selected"/g" "$HOME"/.config/i3/autostart

wall_old="catppuccin_triangle.webp"
    feh_walls_list=$(ls "$HOME"/.config/i3/rices/$selected/walls | grep "png" | head -1)
sed -i "s/"$wall_old"/"$feh_walls_list"/g" "$HOME"/.config/i3/autostart

###----Change GTK Themes
gtk_themes_name='gtk-theme-name='
gtk_themes_name_old="gtk-theme-name=""$i3_rice_in_config"""
gtk_themes_name_new="gtk-theme-name=""$selected"""
sed -i "s/gtk-theme-name=.*/gtk-theme-name="$selected"/g" "$HOME"/.config/gtk-3.0/settings.ini
sed -i "s/gtk-theme-name=.*/gtk-theme-name="$selected"/g" "$HOME"/.config/gtk-4.0/settings.ini
sed -i "s/gtk-theme-name=.*/gtk-theme-name="\"""$selected"""\"/g" "$HOME"/.gtkrc-2.0
sed -i "s/vir0id/${user}/g" "$HOME"/.gtkrc-2.0

###----Change icons
if [[ "$selected" == aline ]]; then
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name="\"Magna-Dark-Icons"\"/g" "$HOME"/.gtkrc-2.0
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=Magna-Dark-Icons/g" "$HOME"/.config/gtk-3.0/settings.ini
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=Magna-Dark-Icons/g" "$HOME"/.config/gtk-4.0/settings.ini
elif [[ "$selected" == brenda ]]; then
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name="\"buuf-nestort"\"/g" "$HOME"/.gtkrc-2.0
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=buuf-nestort/g" "$HOME"/.config/gtk-3.0/settings.ini
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=buuf-nestort/g" "$HOME"/.config/gtk-4.0/settings.ini
elif [[ "$selected" == cristina ]]; then
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name="\"Plataro-master"\"/g" "$HOME"/.gtkrc-2.0
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=Plataro-master/g" "$HOME"/.config/gtk-3.0/settings.ini
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=Plataro-master/g" "$HOME"/.config/gtk-4.0/settings.ini
elif [[ "$selected" == cynthia ]]; then
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name="\"Newaita"\"/g" "$HOME"/.gtkrc-2.0
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=Newaita/g" "$HOME"/.config/gtk-3.0/settings.ini
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=Newaita/g" "$HOME"/.config/gtk-4.0/settings.ini
elif [[ "$selected" == daniela ]]; then
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name="\"Lyra-pink-dark"\"/g" "$HOME"/.gtkrc-2.0
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=Lyra-pink-dark/g" "$HOME"/.config/gtk-3.0/settings.ini
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=Lyra-pink-dark/g" "$HOME"/.config/gtk-4.0/settings.ini
elif [[ "$selected" == emilia ]]; then
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name="\"Magna-Dark-Icons"\"/g" "$HOME"/.gtkrc-2.0
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=Magna-Dark-Icons/g" "$HOME"/.config/gtk-3.0/settings.ini
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=Magna-Dark-Icons/g" "$HOME"/.config/gtk-4.0/settings.ini
elif [[ "$selected" == isabel ]]; then
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name="\"Flat-Remix-Blue-Dark"\"/g" "$HOME"/.gtkrc-2.0
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=Flat-Remix-Blue-Dark/g" "$HOME"/.config/gtk-3.0/settings.ini
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=Flat-Remix-Blue-Dark/g" "$HOME"/.config/gtk-4.0/settings.ini
elif [[ "$selected" == jan ]]; then
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name="\"besgnulinux-mono-cyan"\"/g" "$HOME"/.gtkrc-2.0
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=besgnulinux-mono-cyan/g" "$HOME"/.config/gtk-3.0/settings.ini
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=besgnulinux-mono-cyan/g" "$HOME"/.config/gtk-4.0/settings.ini
elif [[ "$selected" == karla ]]; then
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name="\"Lyra-pink-dark"\"/g" "$HOME"/.gtkrc-2.0
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=Lyra-pink-dark/g" "$HOME"/.config/gtk-3.0/settings.ini
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=Lyra-pink-dark/g" "$HOME"/.config/gtk-4.0/settings.ini
elif [[ "$selected" == marisol ]]; then
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name="\"Zafiro-Nord-Black-Blue"\"/g" "$HOME"/.gtkrc-2.0
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=Zafiro-Nord-Black-Blue/g" "$HOME"/.config/gtk-3.0/settings.ini
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=Zafiro-Nord-Black-Blue/g" "$HOME"/.config/gtk-4.0/settings.ini
elif [[ "$selected" == melissa ]]; then
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name="\"Zafiro-Nord-Black-Blue"\"/g" "$HOME"/.gtkrc-2.0
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=Zafiro-Nord-Black-Blue/g" "$HOME"/.config/gtk-3.0/settings.ini
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=Zafiro-Nord-Black-Blue/g" "$HOME"/.config/gtk-4.0/settings.ini
elif [[ "$selected" == pamela ]]; then
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name="\"Wings-Dark-Icons"\"/g" "$HOME"/.gtkrc-2.0
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=Wings-Dark-Icons/g" "$HOME"/.config/gtk-3.0/settings.ini
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=Wings-Dark-Icons/g" "$HOME"/.config/gtk-4.0/settings.ini
elif [[ "$selected" == silvia ]]; then
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name="\"BeautySolar"\"/g" "$HOME"/.gtkrc-2.0
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=BeautySolar/g" "$HOME"/.config/gtk-3.0/settings.ini
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=BeautySolar/g" "$HOME"/.config/gtk-4.0/settings.ini
fi

i3-msg restart
exit 0