# arm-none-eabi-ar
# Autogenerated from man page /usr/share/man/man1/arm-none-eabi-ar.1.gz
complete -c arm-none-eabi-ar -l help -d 'X Item "--help" Displays the list of command-line options supported by ar and…'
complete -c arm-none-eabi-ar -l version -d 'X Item "--version" Displays the version information of ar and then exits'
complete -c arm-none-eabi-ar -o X32_64 -d 'X Item "-X32_64" ar ignores an initial option spelled -X32_64, for compatibil…'
complete -c arm-none-eabi-ar -l plugin -d 'X Item "--plugin name" The optional command-line switch --plugin name causes …'
complete -c arm-none-eabi-ar -l target -d 'X Item "--target target" The optional command-line switch --target bfdname sp…'
complete -c arm-none-eabi-ar -l output -d 'X Item "--output dirname" The --output option can be used to specify a path t…'
complete -c arm-none-eabi-ar -l record-libdeps -d 'X Item "--record-libdeps libdeps" The --record-libdeps option is identical to…'
complete -c arm-none-eabi-ar -l thin -d 'X Item "--thin" Make the specified archive a thin archive'
complete -c arm-none-eabi-ar -l enable-deterministic-archives -d 'It can be disabled with the U modifier, below.  f 4'
complete -c arm-none-eabi-ar -o X32

