# docker-events
# Autogenerated from man page /usr/share/man/man1/docker-events.1.gz
complete -c docker-events -s f -l filter -d '	Filter output based on conditions provided'
complete -c docker-events -l format -d '	Format output using a custom template: \'json\':             Print in JSON for…'
complete -c docker-events -s h -l help -d '	help for events'
complete -c docker-events -l since -d '	Show all events created since timestamp'
complete -c docker-events -l until -d '	Stream events until this timestamp SEE ALSO'

