# docker-image-inspect
# Autogenerated from man page /usr/share/man/man1/docker-image-inspect.1.gz
complete -c docker-image-inspect -s f -l format -d '	Format output using a custom template: \'json\':             Print in JSON for…'
complete -c docker-image-inspect -s h -l help -d '	help for inspect SEE ALSO'

