# dumpimage
# Autogenerated from man page /usr/share/man/man1/dumpimage.1.gz
complete -c dumpimage -s h -d 'Print usage information and exit'
complete -c dumpimage -s l -d 'Print the header information for R image , including a list of components'
complete -c dumpimage -s o -d 'The file to write the dumped component to'
complete -c dumpimage -s p -d 'Specify the  position of the component to dump'
complete -c dumpimage -s T -d 'Specify the  type of the image'
complete -c dumpimage -s V -d 'Print version information and exit'

