# gpick
# Autogenerated from man page /usr/share/man/man1/gpick.1.gz
complete -c gpick -s v -l version -d 'Print version information. RS . RE'
complete -c gpick -s g -l geometry -d 'Window geometry. RS . RE'
complete -c gpick -s p -l pick -d 'Pick a color'
complete -c gpick -s s -l single -d 'Pick one color and exit. RS . RE'
complete -c gpick -s o -l output -d 'Output picked color. RS . RE'
complete -c gpick -s c -l converter-name -d 'Converter name used for floating picker mode'
complete -c gpick -l no-newline -d 'Output picked color without newline. RS . RE'
complete -c gpick -l no-start -d 'Do not start if not running already.  EXAMPLES'

