# hdGenSchema
# Autogenerated from man page /usr/share/man/man1/hdGenSchema.1.gz
complete -c hdGenSchema -s h -l help -d 'show this help message and exit'
complete -c hdGenSchema -l schemaFile
complete -c hdGenSchema -l srcDir
complete -c hdGenSchema -l dstDir
complete -c hdGenSchema -l all
complete -c hdGenSchema -l list
complete -c hdGenSchema -l names
complete -c hdGenSchema -l validate

