# hyfetch
# Autogenerated from man page /usr/share/man/man1/hyfetch.1.gz
complete -c hyfetch -s h -l help -d 'show this help message and exit'
complete -c hyfetch -s c -l config -d 'Configure hyfetch'
complete -c hyfetch -s C -l config-file -d 'Use another config file'
complete -c hyfetch -s p -l preset -d 'Use preset'
complete -c hyfetch -s m -l mode -d 'Color mode'
complete -c hyfetch -s b -l backend -d 'Choose a *fetch backend'
complete -c hyfetch -l args -d 'Additional arguments pass-through to backend'
complete -c hyfetch -l c-scale -d 'Lighten colors by a multiplier'
complete -c hyfetch -l c-set-l -d 'Set lightness value of the colors'
complete -c hyfetch -l c-overlay -d 'Use experimental overlay color adjusting instead of HSL lightness'
complete -c hyfetch -s V -l version -d 'Check version'
complete -c hyfetch -l june -d 'Show pride month easter egg'
complete -c hyfetch -l debug -d 'Debug mode'
complete -c hyfetch -l distro -l test-distro -d 'Test for a specific distro'
complete -c hyfetch -l ascii-file -d 'Use a specific file for the ascii art SEE ALSO The full documentation for Ver…'

