# inkview
# Autogenerated from man page /usr/share/man/man1/inkview.1.gz
complete -c inkview -s '?' -l help -d 'X Item "-?, --help" Show help options'
complete -c inkview -s V -l version -d 'X Item "-V, --version" Print Inkview version and build date (this is usually …'
complete -c inkview -s f -l fullscreen -d 'X Item "-f, --fullscreen" Launch Inkview in fullscreen mode'
complete -c inkview -s r -l recursive -d 'X Item "-r, --recursive" Search folders specified on the command line recursi…'
complete -c inkview -s t -l timer -d 'X Item "-t, --timer=NUMBER" Change to the next image every NUMBER seconds'
complete -c inkview -s s -l scale -d 'X Item "-s, --scale=NUMBER" Show image scaled by a factor of NUMBER instead o…'
complete -c inkview -s p -l preload

