# jgmenu-pmenu
# Autogenerated from man page /usr/share/man/man1/jgmenu-pmenu.1.gz
complete -c jgmenu-pmenu -s h -l help -d 'Show this help message and exit'
complete -c jgmenu-pmenu -l append-file -d 'Path to menu file to append to the root menu'
complete -c jgmenu-pmenu -l prepend-file -d 'Path to menu file to prepend to the root menu'
complete -c jgmenu-pmenu -l locale -d 'Use a custom locale (e. g.  en_US. UTF-8)'

