# jgmenu_run
# Autogenerated from man page /usr/share/man/man1/jgmenu_run.1.gz
complete -c jgmenu_run -l help -d 'Print help message'
complete -c jgmenu_run -l exec-path -d 'Print path to $libexecdir/jgmenu which is where jgmenu commands are installed'

