# jgmenu
# Autogenerated from man page /usr/share/man/man1/jgmenu.1.gz
complete -c jgmenu -l no-spawn -d 'Redirect command to stdout rather than execute it'
complete -c jgmenu -l checkout -d 'Checkout submenu on startup'
complete -c jgmenu -l config-file -d 'Read config file'
complete -c jgmenu -l icon-size -d 'Specify icon size (22 by default).  If set to 0, icons will not be loaded'
complete -c jgmenu -l at-pointer -d 'Launch menu at mouse pointer'
complete -c jgmenu -l hide-on-startup -d 'Start menu is hidden state'
complete -c jgmenu -l simple -d 'Ignore tint2 settings; Run in short-lived mode (i. e'
complete -c jgmenu -l vsimple -d 'Same as --simple, but also disables icons and ignores jgmenurc'
complete -c jgmenu -l csv-file -d 'Specify menu file (in jgmenu flavoured CSV format)'
complete -c jgmenu -l csv-cmd -d 'Specify command to produce menu data, for example jgmenu_run pmenu'
complete -c jgmenu -l die-when-loaded -d 'Open menu and then exit(0).  Useful for debugging and testing'
complete -c jgmenu -l center -d 'Center align menu horizontally and vertically'
complete -c jgmenu -l persistent -d 'Same as the persistent config option'

