# kwboot
# Autogenerated from man page /usr/share/man/man1/kwboot.1.gz
complete -c kwboot -s b -d 'Handshake; then upload file image over TTY'
complete -c kwboot -s d -d 'Do special handshake on TTY for console debug mode'
complete -c kwboot -s D -d 'Upload file image over TTY without initial handshake'
complete -c kwboot -s p -d 'Obsolete.  Does nothing'
complete -c kwboot -s q -d 'Obsolete.  Does nothing.   It is unknown whether it did something in the past'
complete -c kwboot -s s -d 'Specify custom response timeout when doing handshake.  Default value is 50 ms'
complete -c kwboot -s t -d 'Run a terminal program, connecting standard input and output to . RB TTY'

