# mariadb_config
# Autogenerated from man page /usr/share/man/man1/mariadb_config.1.gz
complete -c mariadb_config -l cflags
complete -c mariadb_config -l include -d 'for more portable options that contain only include paths.  oc o 2. 3'
complete -c mariadb_config -l libmysqld-libs
complete -c mariadb_config -l embedded
complete -c mariadb_config -l libs
complete -c mariadb_config -l libs_r
complete -c mariadb_config -l plugindir
complete -c mariadb_config -l port
complete -c mariadb_config -l socket
complete -c mariadb_config -l variable
complete -c mariadb_config -l version

