# mcdiff
# Autogenerated from man page /usr/share/man/man1/mcdiff.1.gz
complete -c mcdiff -s b -d 'Force black and white display'
complete -c mcdiff -s c -d 'Force color mode on terminals where  mcdiff defaults to black and white'
complete -c mcdiff -s C -d 'Specify a different color set'
complete -c mcdiff -s d -d 'Disable mouse support'
complete -c mcdiff -s f -d 'Display the compiled-in search paths for Midnight Commander files'
complete -c mcdiff -s t -d 'Used only if the code was compiled with S-Lang and terminfo: it makes the Mid…'
complete -c mcdiff -s V -d 'Displays the version of the program'
complete -c mcdiff -s x -d 'Forces xterm mode'

