# remote-viewer
# Autogenerated from man page /usr/share/man/man1/remote-viewer.1.gz
complete -c remote-viewer -s h -l help -d 'X Item "-h, --help" Display command line help summary'
complete -c remote-viewer -s V -l version -d 'X Item "-V, --version" Display program version number'
complete -c remote-viewer -s v -l verbose -d 'X Item "-v, --verbose" Display information about the connection'
complete -c remote-viewer -s z -l zoom -d 'X Item "-z PCT, --zoom=PCT" Zoom level of the display window in percentage'
complete -c remote-viewer -s f -l full-screen -d 'X Item "-f, --full-screen" Start with the windows maximized to fullscreen'
complete -c remote-viewer -l auto-resize -d 'X Item "--auto-resize <always|never>" Controls whether it is permitted to att…'
complete -c remote-viewer -s t -l title -d 'X Item "-t TITLE, --title TITLE" Set the window title to TITLE'
complete -c remote-viewer -s s -l shared -d 'X Item "-s, --shared" Permitted a shared session with multiple clients'
complete -c remote-viewer -l cursor -d 'X Item "--cursor auto|local" Control how the mouse cursor is rendered'
complete -c remote-viewer -l debug -d 'X Item "--debug" Print debugging information'
complete -c remote-viewer -s H -l hotkeys -d 'X Item "-H HOTKEYS, --hotkeys HOTKEYS" Set global hotkey bindings'
complete -c remote-viewer -s K -l keymap -d 'X Item "-K, --keymap" Remap and/or block supplied keypresses to the host'
complete -c remote-viewer -s k -l kiosk -d 'X Item "-k, --kiosk" Start in kiosk mode'
complete -c remote-viewer -l kiosk-quit

