# rmiregistry-openjdk22
# Autogenerated from man page /usr/share/man/man1/rmiregistry-openjdk22.1.gz
complete -c rmiregistry-openjdk22 -o Joption -d 'Used with any Java option to pass the option following the'
complete -c rmiregistry-openjdk22 -s J -s J -d 'Java interpreter'

