# shotcut
# Autogenerated from man page /usr/share/man/man1/shotcut.1.gz
complete -c shotcut -s h -l help -d 'Displays this help'
complete -c shotcut -s v -l version -d 'Displays version information'
complete -c shotcut -l fullscreen -d 'Fill the screen with the Shotcut window'
complete -c shotcut -l noupgrade -d 'Hide upgrade prompt and menu item'
complete -c shotcut -l glaxnimate -d 'Run Glaxnimate instead of Shotcut'
complete -c shotcut -l gpu -d 'Use GPU processing'
complete -c shotcut -l clear-recent -d 'Clear Recent on Exit'
complete -c shotcut -l appdata -d 'The directory for app configuration and data'
complete -c shotcut -l QT_SCALE_FACTOR -d 'The scale factor for a high-DPI screen'
complete -c shotcut -l QT_SCREEN_SCALE_FACTORS -d 'A semicolon-separated list of scale factors for each screen'
complete -c shotcut -l QT_SCALE_FACTOR_ROUNDING_POLICY -d 'How to handle a fractional display scale: Round, Ceil, Floor, RoundPreferFloo…'
complete -c shotcut -l SDL_AUDIODRIVER -d 'Which operating system audio API to use: alsa, arts, dsp, esd, jack, pipewire…'

