# smplayer
# Autogenerated from man page /usr/share/man/man1/smplayer.1.gz
complete -c smplayer -o minigui -d 'Open the mini GUI instead of the default one'
complete -c smplayer -o mpcgui -d 'Open the mpc GUI instead of the default one'
complete -c smplayer -o defaultgui -d 'Open the default gui'
complete -c smplayer -o config-path -d 'Specify the directory for the configuration files (smplayer'
complete -c smplayer -o send-action -d 'Try to make a connection to another running instance and send to it the speci…'
complete -c smplayer -o actions -d '<action_list> is a list of actions separated by spaces'
complete -c smplayer -o close-at-end -d 'Close the main window when the file/playlist finishes'
complete -c smplayer -o no-close-at-end -d 'Do not close the main window when the file/playlist finishes'
complete -c smplayer -o fullscreen -d 'Play the video in fullscreen mode'
complete -c smplayer -o no-fullscreen -d 'Play the video in windowed mode'
complete -c smplayer -o sub -d 'Specify the subtitle file to be loaded (for the first video only)'
complete -c smplayer -o pos -d 'Specify the coordinates where the main window will be displayed'
complete -c smplayer -o size -d 'Specify the size of the main window'
complete -c smplayer -s h -o help -l help -s '?' -d 'Show the help message and then exit'
complete -c smplayer -o add-to-playlist -d 'If there is another instance running, the media will be added to that instanc…'
complete -c smplayer -o disable-server -d 'Disables the server used to communicate with other instances'

