# soxi
# Autogenerated from man page /usr/share/man/man1/soxi.1.gz
complete -c soxi -s V -d 'Set verbosity.  See  sox (1) for details'
complete -c soxi -s T -d 'Used with multiple files; changes the behaviour of  -s ,  -d and  -D to displ…'
complete -c soxi -s t -d 'Show detected file-type'
complete -c soxi -s r -d 'Show sample-rate'
complete -c soxi -s c -d 'Show number of channels'
complete -c soxi -s s -d 'Show number of samples (0 if unavailable)'
complete -c soxi -s d -d 'Show duration in hours, minutes and seconds (0 if unavailable)'
complete -c soxi -s D -d 'Show duration in seconds (0 if unavailable)'
complete -c soxi -s b -d 'Show number of bits per sample (0 if not applicable)'
complete -c soxi -s B -d 'Show the bitrate averaged over the whole file (0 if unavailable)'
complete -c soxi -s p -d 'Show estimated sample precision in bits'
complete -c soxi -s e -d 'Show the name of the audio encoding'
complete -c soxi -s a -d 'Show file comments (annotations) if available'

