# spice-client
# Autogenerated from man page /usr/share/man/man1/spice-client.1.gz
complete -c spice-client -l spice-secure-channels -d 'X Item "--spice-secure-channels=<main,display,inputs,'
complete -c spice-client -l spice-disable-effects -d 'X Item "--spice-disable-effects=<wallpaper,font-smooth,animation,all>" Disabl…'
complete -c spice-client -l spice-color-depth -d 'X Item "--spice-color-depth=<16,32>" Guest display color depth - DEPRECATED '
complete -c spice-client -l spice-ca-file -d 'X Item "--spice-ca-file=<file>" Truststore file for secure connections '
complete -c spice-client -l spice-host-subject -d 'X Item "--spice-host-subject=<host-subject>" Subject of the host certificate …'
complete -c spice-client -l spice-debug -d 'X Item "--spice-debug" Enable Spice-GTK debugging'
complete -c spice-client -l spice-disable-audio -d 'X Item "--spice-disable-audio" Disable audio support'
complete -c spice-client -l spice-disable-usbredir -d 'X Item "--spice-disable-usbredir" Disable USB redirection support'
complete -c spice-client -l spice-usbredir-auto-redirect-filter -d 'X Item "--spice-usbredir-auto-redirect-filter=<filter-string>" Filter selecti…'
complete -c spice-client -l spice-usbredir-redirect-on-connect -d 'X Item "--spice-usbredir-redirect-on-connect=<filter-string>" Filter selectin…'
complete -c spice-client -l spice-gtk-version -d 'X Item "--spice-gtk-version" Display Spice-GTK version information'
complete -c spice-client -l spice-smartcard -d 'X Item "--spice-smartcard" Enable smartcard support'
complete -c spice-client -l spice-smartcard-db -d 'X Item "--spice-smartcard-db=<certificate-db>" Path to the local certificate …'
complete -c spice-client -l spice-smartcard-certificates -d 'X Item "--spice-smartcard-certificates=<certificates>" Certificates to use fo…'
complete -c spice-client -l spice-cache-size -d 'X Item "--spice-cache-size=<bytes>" Image cache size - DEPRECATED '
complete -c spice-client -s 1 -d 'any value.  Several rules can be concatenated with \'|\': rule1|rule2|rule3\\fR'
complete -c spice-client -l spice-glz-window-size

