# urxvt-background
# Autogenerated from man page /usr/share/man/man1/urxvt-background.1.gz
complete -c urxvt-background -l background-expr
complete -c urxvt-background -l background-border
complete -c urxvt-background -l background-interval
complete -c urxvt-background -o pixmap -d 'backgroundPixmap: file[;oplist] 4 Use the specified image file as the window\'…'
complete -c urxvt-background -o tr -d 'transparent: boolean 4 Turn on/off pseudo-transparency by using the root pixm…'
complete -c urxvt-background -o tint -d 'tintColor: colour 4 Tint the transparent background with the given colour'
complete -c urxvt-background -o sh -d 'shading: number 4 Darken (0 .  99) or lighten (101 '
complete -c urxvt-background -o blr -d 'blurRadius: HxV 4 Apply gaussian blur with the specified radius to the transp…'

