# usddiff
# Autogenerated from man page /usr/share/man/man1/usddiff.1.gz
complete -c usddiff -s h -l help -d 'show this help message and exit'
complete -c usddiff -s n -l noeffect -d 'Do not edit either file'
complete -c usddiff -s f -l flatten -d 'Fully compose both layers as Usd Stages and flatten into single layers'
complete -c usddiff -s q -l brief -d 'Do not return full results of diffs.  Passes --brief to the diff command'

