# usdGenSchema
# Autogenerated from man page /usr/share/man/man1/usdGenSchema.1.gz
complete -c usdGenSchema -s t -o hts -d '[schemaPath] [codeGenPath] '
complete -c usdGenSchema -s h -l help -d 'show this help message and exit'
complete -c usdGenSchema -s v -l validate -d 'Verify that the source files are unchanged'
complete -c usdGenSchema -s q -l quiet -d 'Do not output text during execution'
complete -c usdGenSchema -s n -l namespace -d 'Wrap code in this specified namespace'
complete -c usdGenSchema -l templates -d 'Directory containing schema class templates'
complete -c usdGenSchema -l headerTerminatorString -d 'The string used to terminate generated C++ header files, after the custom cod…'

