# usdresolve
# Autogenerated from man page /usr/share/man/man1/usdresolve.1.gz
complete -c usdresolve -s h -l help -d 'show this help message and exit'
complete -c usdresolve -l createContextForAsset -d 'Run CreateDefaultContextForAsset with the given asset path to create the cont…'
complete -c usdresolve -l createContextFromString -d 'Run CreateContextFromString with the given string to create the context used …'
complete -c usdresolve -l anchorPath -d 'Run CreateIdentifier with the input path and this anchor asset path and resol…'

