# usdrecord
# Autogenerated from man page /usr/share/man/man1/usdrecord.1.gz
complete -c usdrecord -s h -l help -d 'show this help message and exit'
complete -c usdrecord -l mask -d 'Limit stage population to these prims, their descendants and ancestors'
complete -c usdrecord -l purposes -d 'Specify which UsdGeomImageable purposes should be included in the renders'
complete -c usdrecord -l sessionLayer -d 'If specified, the stage will be opened with the \'sessionLayer\' in place of th…'
complete -c usdrecord -l disableGpu -d 'Indicates if the GPU should not be used for rendering'
complete -c usdrecord -l disableCameraLight -d 'Indicates if the default camera lights should not be used for rendering'
complete -c usdrecord -l camera -o cam -d 'Which camera to use - may be given as either just the camera\'s prim name (i'
complete -c usdrecord -l defaultTime -s d -d 'explicitly operate at the Default time code (the default behavior is to opera…'
complete -c usdrecord -l frames -s f -d 'specify FrameSpec(s) of the time codes to operate on - A FrameSpec consists o…'
complete -c usdrecord -l complexity -s c -d 'level of refinement to use (default=low)'
complete -c usdrecord -l colorCorrectionMode -o color -d 'the color correction mode to use (default=sRGB)'
complete -c usdrecord -l renderer -s r -d 'Hydra renderer plugin to use when generating images'
complete -c usdrecord -l imageWidth -s w -d 'Width of the output image'
complete -c usdrecord -l enableDomeLightVisibility -d 'Show the dome light background in the rendered output'
complete -c usdrecord -l renderPassPrimPath -o rp -d 'Specify the Render Pass Prim to use to render the given usdFile'
complete -c usdrecord -l renderSettingsPrimPath -o rs -d 'Specify the Render Settings Prim to use to render the given usdFile'

