# usdstitchclips
# Autogenerated from man page /usr/share/man/man1/usdstitchclips.1.gz
complete -c usdstitchclips -s r -s e -s p -d '[--clipSet CLIPSET] [--activeOffset ACTIVEOFFSET] [--interpolateMissingClipVa…'
complete -c usdstitchclips -s h -l help -d 'show this help message and exit'
complete -c usdstitchclips -s o -l out -d 'specify the filename for the top-level result file, which also serves as base…'
complete -c usdstitchclips -s c -l clipPath -d 'specify a prim path at which to begin stitching clip data'
complete -c usdstitchclips -s s -l startTimeCode -d 'specify the time at which the clips will become active'
complete -c usdstitchclips -l stride -d 'specify a stride for the numeric component of filenames for template metadata'
complete -c usdstitchclips -l endTimeCode -d 'specify the time at which the clips will cease being active'
complete -c usdstitchclips -s t -l templateMetadata -d 'author template clip metadata in the root layer'
complete -c usdstitchclips -l templatePath -d 'specify a template asset path to author'
complete -c usdstitchclips -l clipSet -d 'specify a named clipSet in which to author clip metadata, so that multiple se…'
complete -c usdstitchclips -l activeOffset -d 'specify an offset for template-based clips, offsetting the frame number of ea…'
complete -c usdstitchclips -l interpolateMissingClipValues -d 'specify whether values for clips without authored samples are interpolated fr…'
complete -c usdstitchclips -s n -l noComment -d 'do not write a comment specifying how the usd file was generated'

