# usdstitch
# Autogenerated from man page /usr/share/man/man1/usdstitch.1.gz
complete -c usdstitch -s h -l help -d 'show this help message and exit'
complete -c usdstitch -s o -l out -d 'specify a file to write out to'

