# viewnior
# Autogenerated from man page /usr/share/man/man1/viewnior.1.gz
complete -c viewnior -l slideshow -d 'Start in slideshow'
complete -c viewnior -l fullscreen -d 'Start in full screen mode'
complete -c viewnior -s '?' -l help -d 'Show this help and exit'
complete -c viewnior -l version -d 'Show version information and exit SEE ALSO'

