# virt-viewer
# Autogenerated from man page /usr/share/man/man1/virt-viewer.1.gz
complete -c virt-viewer -s h -l help -d 'X Item "-h, --help" Display command line help summary'
complete -c virt-viewer -s V -l version -d 'X Item "-V, --version" Display program version number'
complete -c virt-viewer -s v -l verbose -d 'X Item "-v, --verbose" Display information about the connection'
complete -c virt-viewer -s c -l connect -d 'X Item "-c URI, --connect=URI" Specify the hypervisor connection URI'
complete -c virt-viewer -s w -l wait -d 'X Item "-w, --wait" Wait for the domain to start up before attempting to conn…'
complete -c virt-viewer -s r -l reconnect -d 'X Item "-r, --reconnect" Automatically reconnect to the domain if it shuts do…'
complete -c virt-viewer -s z -l zoom -d 'X Item "-z PCT, --zoom=PCT" Zoom level of the display window in percentage'
complete -c virt-viewer -s d -l direct -d 'X Item "-d, --direct" Do not attempt to tunnel the console over SSH, even if …'
complete -c virt-viewer -s a -l attach -d 'X Item "-a, --attach" Instead of making a direct TCP/UNIX socket connection t…'
complete -c virt-viewer -s f -l full-screen -d 'X Item "-f, --full-screen" Start with the window maximised to fullscreen '
complete -c virt-viewer -l auto-resize -d 'X Item "--auto-resize <always|never>" Controls whether it is permitted to att…'
complete -c virt-viewer -s s -l shared -d 'X Item "-s, --shared" Permitted a shared session with multiple clients'
complete -c virt-viewer -l cursor -d 'X Item "--cursor auto|local" Control how the mouse cursor is rendered'
complete -c virt-viewer -l debug -d 'X Item "--debug" Print debugging information'
complete -c virt-viewer -s H -l hotkeys -d 'X Item "-H HOTKEYS, --hotkeys HOTKEYS" Set global hotkey bindings'
complete -c virt-viewer -s K -l keymap -d 'X Item "-K, --keymap" Remap and/or block supplied keypresses to the host'
complete -c virt-viewer -s k -l kiosk -d 'X Item "-k, --kiosk" Start in kiosk mode'
complete -c virt-viewer -l kiosk-quit -d 'X Item "--kiosk-quit <never|on-disconnect>" By default, when kiosk mode is en…'
complete -c virt-viewer -l id -l uuid -l domain-name

