# web-greeter
# Autogenerated from man page /usr/share/man/man1/web-greeter.1.gz
complete -c web-greeter -s h -l help -d 'Shows the help'
complete -c web-greeter -s v -l version -d 'Print program version'
complete -c web-greeter -l debug -d 'Forces the greeter to run in debug mode'
complete -c web-greeter -l normal -d 'Forces the greeter to run in normal mode'
complete -c web-greeter -l list -d 'Shows the available themes'

