# Xdialog
# Autogenerated from man page /usr/share/man/man1/Xdialog.1.gz
complete -c Xdialog -l tailbox -l textbox -l editbox -d 'TP  --password | --password=1|2'
complete -c Xdialog -l 2inputsbox -l 3inputsbox -l password -d 'TP  --editable'
complete -c Xdialog -l combobox -d 'TP  --time-stamp | --date-stamp'
complete -c Xdialog -l logbox -d 'TP  --reverse'
complete -c Xdialog -l menubox -l checklist -l radiolist -d 'TP  --item-help'
complete -c Xdialog -l buildlist -l treeview -l item-help -d 'TP  --default-item <tag>'
complete -c Xdialog -l infobox -l gauge -l progress -d 'TP  --no-buttons'
complete -c Xdialog -l fselect -l dselect -d 'TP  --default-no'
complete -c Xdialog -l wizard -d 'TP  --wizard'
complete -c Xdialog -l msgbox -d 'TP  --help <help>'
complete -c Xdialog -l wmclass
complete -c Xdialog -l rc-file
complete -c Xdialog -l backtitle
complete -c Xdialog -l title
complete -c Xdialog -l allow-close -l no-close
complete -c Xdialog -l screen-center -l under-mouse -l auto-placement
complete -c Xdialog -l center -l right -l left -l fill
complete -c Xdialog -l no-wrap -l wrap
complete -c Xdialog -l cr-wrap -l no-cr-wrap
complete -c Xdialog -l stderr -l stdout
complete -c Xdialog -l separator -l separate-output
complete -c Xdialog -l buttons-style
complete -c Xdialog -l fixed-font -d 'This option is for use with --tailbox, --textbox and --editbox'
complete -c Xdialog -l editable -d 'This option is for use with --combobox'
complete -c Xdialog -l time-stamp -l date-stamp -d 'This option is for use with --logbox'
complete -c Xdialog -l reverse -d 'This option is for use with --logbox'
complete -c Xdialog -l keep-colors -d 'This option is for use with --logbox'
complete -c Xdialog -l interval -d 'This option may be used with input(s) boxes, combo box, range(s) boxes, spin(…'
complete -c Xdialog -l timeout -d 'This option may be used with all but infobox, gauge and progress widgets'
complete -c Xdialog -l no-tags -d 'This option is for use with --menubox, --checklist and --radiolist'
complete -c Xdialog -l default-item -d 'This option is for use with --menubox'
complete -c Xdialog -l icon -d 'This option is for use with any widget accepting a <text> parameter'
complete -c Xdialog -l no-ok -d 'This option is for use with --tailbox and --logbox'
complete -c Xdialog -l no-cancel -d 'This option may be used with all but --infobox, --gauge and --progress'
complete -c Xdialog -l no-buttons -d 'This option may be used with --textbox, --tailbox, --logbox, --infobox, --fse…'
complete -c Xdialog -l default-no -d 'This option may be used with all widgets with a "Cancel" or "No" button'
complete -c Xdialog -l help -d 'This option may be used with all but --infobox, --gauge and --progress'
complete -c Xdialog -l print -d 'This option is for use with --tailbox, --textbox and --editbox'
complete -c Xdialog -l check -d 'This option may be used with all but --infobox, --gauge and --progress'
complete -c Xdialog -l ok-label -d 'This option may be used with all widgets with a "OK" or "Yes" button'
complete -c Xdialog -l cancel-label -d 'This option may be used with all widgets with a "Cancel" or "No" button'
complete -c Xdialog -l beep -d 'This option may be used with all widgets'
complete -c Xdialog -l beep-after -d 'This option may be used with all widgets'
complete -c Xdialog -l begin -d 'This option may be used with all widgets'
complete -c Xdialog -l ignore-eof -d 'This option may be used with --infobox and --gauge'
complete -c Xdialog -l smooth -d 'This option is for use with --tailbox and --logbox'
complete -c Xdialog -l 'yesno		<text>'
complete -c Xdialog -l 'msgbox		<text>'
complete -c Xdialog -l 'infobox		<text>'
complete -c Xdialog -l 'gauge		<text>'
complete -c Xdialog -l 'progress	<text>'
complete -c Xdialog -l 'inputbox	<text>'
complete -c Xdialog -l '2inputsbox	<text>'
complete -c Xdialog -l '3inputsbox	<text>'
complete -c Xdialog -l 'combobox	<text>'
complete -c Xdialog -l 'rangebox	<text>'
complete -c Xdialog -l '2rangesbox	<text>'
complete -c Xdialog -l '3rangesbox	<text>'
complete -c Xdialog -l 'spinbox		<text>'
complete -c Xdialog -l '2spinsbox	<text>'
complete -c Xdialog -l '3spinsbox	<text>'
complete -c Xdialog -l 'textbox		<file>'
complete -c Xdialog -l 'editbox		<file>'
complete -c Xdialog -l 'tailbox		<file>'
complete -c Xdialog -l 'logbox		<file>'
complete -c Xdialog -l 'menubox		<text>'
complete -c Xdialog -l 'checklist	<text>'
complete -c Xdialog -l 'radiolist	<text>'
complete -c Xdialog -l 'buildlist	<text>'
complete -c Xdialog -l 'treeview	<text>'
complete -c Xdialog -l 'fselect		<file>'
complete -c Xdialog -l 'dselect		<directory>'
complete -c Xdialog -l 'colorsel	<text>'
complete -c Xdialog -l 'fontsel		<font'
complete -c Xdialog -l 'calendar	<text>'
complete -c Xdialog -l 'timebox		<text>'
complete -c Xdialog -l version -l print-version

