# zscroll
# Autogenerated from man page /usr/share/man/man1/zscroll.1.gz
complete -c zscroll -s h -l help -d 'Print help text'
complete -c zscroll -s l -l length -d 'Specify a character length for the text to be scrolled in'
complete -c zscroll -s r -l reverse -d 'Specify whether the text should be scrolled in reverse order (from left to ri…'
complete -c zscroll -s b -l before-text -d 'Specify static padding text that will always be displayed to the left of the …'
complete -c zscroll -s a -l after-text -d 'Specify static padding text that will always be displayed to the right of the…'
complete -c zscroll -s p -l scroll-padding -d 'Specify padding text that will be displayed in between the start and end of d…'
complete -c zscroll -s s -l scroll -d 'Specify whether or not the text should be scrolled'
complete -c zscroll -s m -l match-text -d 'Specify a regexp search term to look for in the output of the corresponding -…'
complete -c zscroll -s M -l match-command -d 'Specify a command to search the output of'
complete -c zscroll -s d -l delay -d 'Specify the delay between scroll steps.  (default: 0. 4)'
complete -c zscroll -s u -l update-check -d 'Specify that the positional argument refers to a command that should be run t…'
complete -c zscroll -s U -l update-interval -d 'Specify the time in seconds to wait in between running update checking comman…'
complete -c zscroll -s e -l eval-in-shell -d 'Executes -M/--match-command and the positional argument in the shell (-u/--up…'
complete -c zscroll -s n -l newline -d 'Add a newline after every update/step (may be necessary for use with panels)'
complete -c zscroll -s t -l timeout -d 'Time in seconds to run before closing'

