#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/i3"
STYLE="tealize"
RASI="$DIR/rices/$STYLE/rofi/runner.rasi"

# Run
rofi \
    -show run \
	-theme ${RASI}
