#!/usr/bin/env bash
#  ███████╗██╗  ██╗████████╗███████╗██████╗ ███╗   ██╗ █████╗ ██╗
#  ██╔════╝╚██╗██╔╝╚══██╔══╝██╔════╝██╔══██╗████╗  ██║██╔══██╗██║
#  █████╗   ╚███╔╝    ██║   █████╗  ██████╔╝██╔██╗ ██║███████║██║
#  ██╔══╝   ██╔██╗    ██║   ██╔══╝  ██╔══██╗██║╚██╗██║██╔══██║██║
#  ███████╗██╔╝ ██╗   ██║   ███████╗██║  ██║██║ ╚████║██║  ██║███████╗
#  ╚══════╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝╚══════╝
#
#              ██████╗ ██╗   ██╗██╗     ███████╗███████╗
#              ██╔══██╗██║   ██║██║     ██╔════╝██╔════╝
#              ██████╔╝██║   ██║██║     █████╗  ███████╗
#              ██╔══██╗██║   ██║██║     ██╔══╝  ╚════██║
#              ██║  ██║╚██████╔╝███████╗███████╗███████║
#              ╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚══════╝╚══════╝
#	[Author] : gh0stzk
#	 [Url]   : https://github.com/gh0stzk/dotfiles
#

wid=$1
class=$2
instance=$3
consequences=$4

result() {
    eval "$consequences"
    [ "$state" ] || echo "$1"
}

case "$class" in
    FloaTerm)
        result "state=floating center=on desktop=^1"
        ;;
    kitty)
        kitty desktop=^1"
        ;;
    Updating)
        result "state=floating sticky=on center=on"
        ;;
    mpv)
        result "state=floating focus=on rectangle=849x477+0+0 center=on"
        ;;
    Viewnior)
        result "state=floating focus=on center=on"
        ;;
    whatsdesk|TelegramDesktop)
        result "desktop=^4 follow=on"
        ;;
    retroarch)
        result "state=pseudo_tiled desktop=^6"
        ;;
    Pavucontrol)
        result "state=floating center=on"
        ;;
    Virt-manager)
        result "state=floating desktop=^5 follow=on center=on"
        ;;
    Thunar)
        result "desktop=^3 follow=on"
        ;;
    Blender)
        result "desktop=^5 follow=on"
        ;;
    code-oss)
        result "desktop=^6 follow=on"
        ;;
    firefox|Navigator)
        result "desktop=^3 follow=on desktop=^1"
        ;;
    Transmission-gtk)
        result "desktop=^6 follow=on"
        ;;
    Spotify)
        result "state=floating desktop=^6 follow=on center=on"
        ;;
esac

case "$instance" in
    Toolkit)
        result "state=floating sticky=on rectangle=500x290+1054+593"
        ;;
esac
