;  ╔═╗╦ ╦╔═╗╔╦╗╔═╗╔╦╗  ╦  ╦╔═╗╦═╗╦╔═╗╔╗ ╦  ╔═╗╔═╗
;  ╚═╗╚╦╝╚═╗ ║ ║╣ ║║║  ╚╗╔╝╠═╣╠╦╝║╠═╣╠╩╗║  ║╣ ╚═╗
;  ╚═╝ ╩ ╚═╝ ╩ ╚═╝╩ ╩   ╚╝ ╩ ╩╩╚═╩╩ ╩╚═╝╩═╝╚═╝╚═╝
; The variables for the polybar modules are taken from this file.

;; Edit according to your system
;; Run `ls -1 /sys/class/power_supply/` to list list batteries and adapters.
;; Run `ls -1 /sys/class/backlight/` to list available graphics cards.
;; Run `ip link | awk '/state UP/ {print $2}' | tr -d :` to get active network interface.

[system]
sys_adapter = AC
sys_battery = BAT0
sys_graphics_card = nvidia_0
sys_network_interface = enp59s0
sys_wireless_interface = wlan0
sys_monitor = DP-0

[fonts]
font-0 = MesloLGS NF:style=Regular:pixelsize=10;4
font-1 = Symbols Nerd Font:size=12;3
# font-2 = (Custom font here)

[theme]
panel_borders = 0
corn_radius = 9.0

[settings]
monitor-strict = false
override-redirect = true