viewport_navigation_events = [
    'MIDDLEMOUSE', 'WHEELUPMOUSE', 'WHEELDOWNMOUSE',
    'TRACKPADPAN', 'TRACKPADZOOM', 'MOUSEROTATE', 'MOUSESMARTZOOM',
    'NDOF_MOTION'
]

viewport_navigation_keys = ['NUMPAD_1', 'NUMPAD_2', 'NUMPAD_3', 'NUMPAD_5', 'NUMPAD_7']

free_key = ['TAB', 'G', 'R']

fluent_modifiers_name = {
    'mirror': '.f_Mirror',
    'array_x': '.f_Array_X',
    'array_y': '.f_Array_Y',
    'array_z': '.f_Array_Z',
    'center_array_x': '.f_Move_Center_X',
    'center_array_y': '.f_Move_Center_Y',
    'center_array_z': '.f_Move_Center_Z',
    'first_solidify': '.f_First_Solidify',
    'second_solidify': '.f_Second_Solidify',
    'first_bevel': '.f_First_Bevel.',
    'second_bevel_top': '.f_Second_Bevel_Top',
    'second_bevel_bottom': '.f_Second_Bevel_Bottom',
    'taper_x': '.f_Taper_X',
    'taper_y': '.f_Taper_Y',
    'taper_z': '.f_Taper_Z',
    'circular_displace': '.f_Circular_Displace',
    'circular_array': '.f_Circular_Array',
    'radius': '.f_Radius',
    'inner_radius': '.f_InnerRadius',
    'screw': '.f_Screw',
    'screw_2': '.f_Screw_Again',
    'decimate': '.f_Decimate',
    'curve_triangulate': '.f_Curve_Triangulate',
    'curve_subdivision': '.f_Curve_Subdiv',
    'curve_decimate': '.f_Curve_Decimate',
    'path_height': '.f_Path_Height',
    'path_displace': '.f_Path_Displace',
    'path_decimate': '.f_Path_Decimate',
    'inset_solidify': '.f_Inset_Solidify',
    'revolver_decimate': '.f_Revolver_Decimate',
    'outer_bevel': '.f_outer_bevel',
    'empty_circular': '.f_empty_circular_array',
    'scale': '.f_scale',
    'rotate': '.f_rotate',
    'boolean': '.f_boolean',
    'weld': '.f_weld',
    'data_transfer': '.f_Data_Transfer',
    'weighted_normal': '.f_Weighted_Normal',
    'head_screw': '.f_Head_Screw',
    'frame': '.f_Frame',
    'pre_chamfer': '.f_Pre_Chamfer',
    'chamfer': '.f_Chamfer',
    'pre_second_bevel_bottom': '.f_Pre_Second_Bevel_Bottom',
    'pre_second_bevel_top': '.f_Pre_Second_Bevel_Top',
    'bevel': '.f_bevel',
    'geometry_nodes': '.f_geometry_nodes',
    'auto_smooth': '.f_auto_smooth'
}


WIDGET_ACTIONS = ['MIRROR', 'TAPER', 'ARRAY', 'DIMENSIONS', 'ROTATION', 'REUSE']

fluent_stack_order = {
    'box': [
        'scale',
        'rotate',
        'taper_x',
        'taper_y',
        'first_bevel',
        'first_solidify',
        'taper_z',
        'pre_second_bevel_bottom',
        'second_bevel_bottom',
        'pre_second_bevel_top',
        'second_bevel_top',
        'second_solidify',
        'boolean',
        'pre_chamfer',
        'chamfer',
        'frame',
        'array_x',
        'array_y',
        'array_z',
        'center_array_x',
        'center_array_y',
        'center_array_z',
        'circular_array',
        'mirror',
        'auto_smooth',
    ],
    'poly': [
        'scale',
        'rotate',
        'curve_triangulate',
        'curve_subdivision',
        'curve_decimate',
        'taper_x',
        'taper_y',
        'first_bevel',
        'first_solidify',
        'taper_z',
        'pre_second_bevel_bottom',
        'second_bevel_bottom',
        'pre_second_bevel_top',
        'second_bevel_top',
        'second_solidify',
        'boolean',
        'pre_chamfer',
        'chamfer',
        'frame',
        'array_x',
        'array_y',
        'array_z',
        'center_array_x',
        'center_array_y',
        'center_array_z',
        'circular_array',
        'mirror',
        'auto_smooth',
    ],
    'path': [
        'path_displace',
        'scale',
        'rotate',
        'taper_x',
        'taper_y',
        'first_bevel',
        'path_height',
        'path_decimate',
        'first_solidify',
        'taper_z',
        'pre_second_bevel_bottom',
        'second_bevel_bottom',
        'pre_second_bevel_top',
        'second_bevel_top',
        'second_solidify',
        'boolean',
        'array_x',
        'array_y',
        'array_z',
        'center_array_x',
        'center_array_y',
        'center_array_z',
        'circular_array',
        'mirror',
        'auto_smooth',
    ],
    'prism': [
        'radius',
        'inner_radius',
        'screw',
        'decimate',
        'scale',
        'rotate',
        'taper_x',
        'taper_y',
        'first_solidify',
        'taper_z',
        'pre_second_bevel_bottom',
        'second_bevel_bottom',
        'pre_second_bevel_top',
        'second_bevel_top',
        'second_solidify',
        'boolean',
        'pre_chamfer',
        'chamfer',
        'frame',
        'array_x',
        'array_y',
        'array_z',
        'center_array_x',
        'center_array_y',
        'center_array_z',
        'circular_array',
        'mirror',
        'auto_smooth',
    ],
    'sphere': [
        'radius',
        'screw',
        'screw_2',
        'scale',
        'rotate',
        'taper_x',
        'taper_y',
        'taper_z',
        'second_solidify',
        'boolean',
        'array_x',
        'array_y',
        'array_z',
        'center_array_x',
        'center_array_y',
        'center_array_z',
        'circular_array',
        'mirror',
        'auto_smooth',
    ],
    'revolver': [
        'first_bevel',
        'screw',
        'decimate',
        'scale',
        'rotate',
        'taper_x',
        'taper_y',
        'taper_z',
        'pre_second_bevel_bottom',
        'second_bevel_bottom',
        'pre_second_bevel_top',
        'second_bevel_top',
        'second_solidify',
        'boolean',
        'array_x',
        'array_y',
        'array_z',
        'center_array_x',
        'center_array_y',
        'center_array_z',
        'circular_array',
        'mirror',
        'auto_smooth',
    ],
    'unknow': [],
    'plate': [
        'first_solidify',
        'mirror'
    ],
    'pipe': [
        'weld',
        'bevel',
        'geometry_nodes',
        'mirror'
    ],
    'wire': [
        'geometry_nodes',
        'mirror'
    ],
    'head_screw': [
        'head_screw',
        'mirror'
    ]
}

fluent_dimension_mods = [
    fluent_modifiers_name['scale'],
    fluent_modifiers_name['rotate'],
    fluent_modifiers_name['frame'],
    fluent_modifiers_name['pre_chamfer'],
    fluent_modifiers_name['chamfer'],
    fluent_modifiers_name['first_solidify'],
    fluent_modifiers_name['second_solidify'],
    fluent_modifiers_name['radius'],
    fluent_modifiers_name['screw'],
    fluent_modifiers_name['path_height'],
]

fluent_modifiers_to_ignore_for_reuse = [
    fluent_modifiers_name['scale'],
    fluent_modifiers_name['rotate'],
    fluent_modifiers_name['radius'],
    fluent_modifiers_name['screw'],
    fluent_modifiers_name['screw_2'],
    fluent_modifiers_name['decimate'],
    fluent_modifiers_name['boolean'],
    fluent_modifiers_name['array_x'],
    fluent_modifiers_name['array_y'],
    fluent_modifiers_name['array_z'],
    fluent_modifiers_name['center_array_x'],
    fluent_modifiers_name['center_array_y'],
    fluent_modifiers_name['center_array_z'],
    fluent_modifiers_name['circular_array'],
    fluent_modifiers_name['mirror'],
]

fluent_modifiers_simple_copy = [
    fluent_modifiers_name['pre_second_bevel_bottom'],
    fluent_modifiers_name['second_bevel_bottom'],
    fluent_modifiers_name['pre_second_bevel_top'],
    fluent_modifiers_name['second_bevel_top'],
    fluent_modifiers_name['frame'],
    fluent_modifiers_name['taper_x'],
    fluent_modifiers_name['taper_y'],
    fluent_modifiers_name['taper_z'],
    fluent_modifiers_name['path_decimate'],
    fluent_modifiers_name['path_height'],
    fluent_modifiers_name['path_displace'],
    fluent_modifiers_name['curve_decimate'],
    fluent_modifiers_name['curve_subdivision'],
    fluent_modifiers_name['curve_triangulate'],
]

fluent_modifiers_to_exclude_per_type = {
    'box': [
        fluent_modifiers_name['path_decimate'],
        fluent_modifiers_name['path_height'],
        fluent_modifiers_name['path_displace'],
        fluent_modifiers_name['curve_decimate'],
        fluent_modifiers_name['curve_subdivision'],
        fluent_modifiers_name['curve_triangulate'],
    ],
    'poly': [
        fluent_modifiers_name['path_decimate'],
        fluent_modifiers_name['path_height'],
        fluent_modifiers_name['path_displace'],
    ],
    'path': [
        fluent_modifiers_name['pre_chamfer'],
        fluent_modifiers_name['chamfer'],
        fluent_modifiers_name['curve_decimate'],
        fluent_modifiers_name['curve_subdivision'],
        fluent_modifiers_name['curve_triangulate'],
    ],
    'prism': [
        fluent_modifiers_name['first_bevel'],
        fluent_modifiers_name['path_decimate'],
        fluent_modifiers_name['path_height'],
        fluent_modifiers_name['path_displace'],
        fluent_modifiers_name['curve_decimate'],
        fluent_modifiers_name['curve_subdivision'],
        fluent_modifiers_name['curve_triangulate'],
    ],
    'sphere': [
        fluent_modifiers_name['first_solidify'],
        fluent_modifiers_name['first_bevel'],
        fluent_modifiers_name['frame'],
        fluent_modifiers_name['chamfer'],
        fluent_modifiers_name['pre_second_bevel_bottom'],
        fluent_modifiers_name['second_bevel_bottom'],
        fluent_modifiers_name['pre_second_bevel_top'],
        fluent_modifiers_name['second_bevel_top'],
        fluent_modifiers_name['path_decimate'],
        fluent_modifiers_name['path_height'],
        fluent_modifiers_name['path_displace'],
        fluent_modifiers_name['curve_decimate'],
        fluent_modifiers_name['curve_subdivision'],
        fluent_modifiers_name['curve_triangulate'],
    ],
    'revolver': [
        fluent_modifiers_name['first_solidify'],
        fluent_modifiers_name['frame'],
        fluent_modifiers_name['chamfer'],
        fluent_modifiers_name['path_decimate'],
        fluent_modifiers_name['path_height'],
        fluent_modifiers_name['path_displace'],
        fluent_modifiers_name['curve_decimate'],
        fluent_modifiers_name['curve_subdivision'],
        fluent_modifiers_name['curve_triangulate'],
    ]
}
