#!/usr/bin/env bash
# ----------------------------------
# Author: Quinn Wilby
# Email:  contact@loki.moe
# Github: https://github.com/druanae
# ----------------------------------
# This script will get the workspace Information for i3wm
# and output a lemonbar-formatted string.
# To use this you will need the jq package, otherwise the only dependency is i3.
# ----------------------------------
# To change the colours edit the col variables at the start.
# To change the workspace names edit the values in the $workspaces var
# To set the secondary monitor edit the $Sec_Mon variable with the monitor name.

groups() {
    # Variable Declarations
    col_focused="#0000FF"
    col_inactive_focused="#00FF00"
    col_inactive="#666"
    col_inactive_secondary="#666600"
    col_urgent="#FF0000"
    col_empty="#444"
    Sec_Mon="HDMI-0"

    # Workspace Names
    declare -a workspaces=(
        "1" # WS01
        "2" # WS02
        "3" # WS03
        "4" # WS04
        "5" # WS05
        "6" # WS06
        "7" # WS07
        "8" # WS08 
        "9" # WS09 
        "10" # WS10
    )
    # Get Workspace Information
    status="$(i3-msg -t get_workspaces)"
    
    list=$(echo $status | jq '.[].num' | wc -l)
    list=$((list - 1))
    for ((i=0;i<=$list;i++))
    do  
        focused=$(echo $status | jq ".[$i].focused")
        visible=$(echo $status | jq ".[$i].visible")
        urgent=$(echo $status | jq ".[$i].urgent")
        output=$(echo $status | jq ".[$i].output")
        num=$(($(echo $status | jq ".[$i].num") - 1))
        if [ $visible == "true" ]; then
            if [ $focused == "true" ]; then
                workspaces[$num]="%{F$col_focused}${workspaces[$num]}%{F-}"
            else
                workspaces[$num]="%{F$col_inactive_focused}${workspaces[$num]}%{F-}"
            fi
        elif [ $urgent == "true" ]; then
            workspaces[$num]="%{F$col_urgent}${workspaces[$num]}%{F-}"
        elif [ $output == "$Sec_Mon" ]; then
            workspaces[$num]="%{F$col_inactive_secondary}${workspaces[$num]}%{F-}"
        else
            workspaces[$num]="%{F$col_inactive}${workspaces[$num]}%{F-}"
        fi  
    done
    declare outstring
    for i in {0..9}; do
        outstring="${outstring}%{F$col_empty}${workspaces[$i]}%{F-} "
    done
    echo $outstring

}
groups