#!/usr/bin/env bash
#   █████╗ ██████╗ ██████╗ ███████╗    ██╗      █████╗ ██╗   ██╗███╗   ██╗ ██████╗██╗  ██╗███████╗██████╗
#  ██╔══██╗██╔══██╗██╔══██╗██╔════╝    ██║     ██╔══██╗██║   ██║████╗  ██║██╔════╝██║  ██║██╔════╝██╔══██╗
#  ███████║██████╔╝██████╔╝███████╗    ██║     ███████║██║   ██║██╔██╗ ██║██║     ███████║█████╗  ██████╔╝
#  ██╔══██║██╔═══╝ ██╔═══╝ ╚════██║    ██║     ██╔══██║██║   ██║██║╚██╗██║██║     ██╔══██║██╔══╝  ██╔══██╗
#  ██║  ██║██║     ██║     ███████║    ███████╗██║  ██║╚██████╔╝██║ ╚████║╚██████╗██║  ██║███████╗██║  ██║
#  ╚═╝  ╚═╝╚═╝     ╚═╝     ╚══════╝    ╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
# Script to control prefered apps to launch for all themes
# Author: z0mbi3
# url:    https://github.com/gh0stzk

WIDGET_DIR="$HOME/.config/bspwm/eww"

case "$1" in
    --menu)
        rofi -show drun -theme "$HOME"/.config/bspwm/scripts/Launcher.rasi 
        ;;
    --rice)
        RiceSelector
        ;;
    --terminal)
        kitty 
        ;;
    --floating)
        kitty --class=FloaTerm -o initial_window_width=842 -o initial_window_height=495
        ;;
    --update)
        kitty --hold --class=FloaTerm -o initial_window_width=842 -o initial_window_height=495 -e Updates --update-aur
        ;;
    --update-garuda)
        kitty --hold --class=FloaTerm -o initial_window_width=842 -o initial_window_height=495 -e Updates --update-garuda
        ;;
    --checkupdates)
        kitty --hold --class=Updating -o initial_window_width=457 -o initial_window_height=496 -e Updates --print-updates
        ;;
    --netmanager)
		NetManagerDM
		;;
    --ranger)
        kitty --hold --class=FloaTerm -o initial_window_width=844 -o initial_window_height=328 -e ranger
        ;;
    --nvim)
        kitty -e nvim
        ;;
    --music)
        kitty --class=FloaTerm -o initial_window_width=637 -o initial_window_height=412 -e ncmpcpp
        ;;
    --fetch)
        kitty --class=FloaTerm -o initial_window_width=394 -o initial_window_height=580 -e ~/.local/bin/sysfetch
        ;;
        # Apps
    --filemanager)
        thunar
        ;;
    --browser)
        firefox
        ;;
    --editor)
        geany
        ;;
    --telegram)
        telegram-desktop
        ;;
    --blender)
        blender
        ;;
    --gimp)
        gimp
        ;;
    --code-oss)
        code-oss
        ;;
    --ristretto)
        ristretto
        ;;
    --kodi)
        kodi
        ;;
    --whats)
        whatsdesk --disable-gpu
        ;;
    --soundcontrol)
        pavucontrol
        ;;
        # Eww Widgets
    --powermenu)
        eww -c "$WIDGET_DIR" open --toggle powermenu
        ;;
    --usercard)
        eww -c "$WIDGET_DIR" open --toggle launchermenu
        ;;
    --player)
        eww -c "$WIDGET_DIR" open --toggle music
        ;;
    --calendar)
        eww -c "$WIDGET_DIR" open --toggle date
        ;;
    *)
        echo "Invalid Option"
        ;;
esac
